image: "rust:latest"

# Use cargo to test the project
test:cargo:
    only:
        changes:
            - "execfn/**/*" 
    script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
