[package]
name = "evalx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
std-expr = { path="../express-std"}
express = { path="../express-core"}
rayon = "1.5.2"
